# Generated by Django 4.2.5 on 2023-10-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_payment_room_reservation_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Student',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='Telno',
            new_name='telno',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='PaymentDate',
            new_name='paymentDate',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='PaymentMethod',
            new_name='paymentMethod',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='CheckInDate',
            new_name='checkInDate',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='CheckOutDate',
            new_name='checkOutDate',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Hostel',
            new_name='hostel',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Reservation',
            new_name='reservation',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Room_number',
            new_name='room_number',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Room_type',
            new_name='room_type',
        ),
    ]
