# Generated by Django 4.2.5 on 2023-10-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_rename_date_feedback_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Feedback.hostel'),
        ),
    ]
