# Generated by Django 4.2.5 on 2023-10-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0006_alter_hostel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='occupants',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
