# Generated by Django 4.2.5 on 2023-10-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0007_room_occupants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
