# Generated by Django 4.2.5 on 2023-10-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0010_alter_room_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
