# Generated by Django 4.2.5 on 2023-10-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0012_alter_room_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image1',
            field=models.ImageField(null=True, upload_to='static/rooms/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.ImageField(null=True, upload_to='static/rooms/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image3',
            field=models.ImageField(null=True, upload_to='static/rooms/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image4',
            field=models.ImageField(null=True, upload_to='static/rooms/'),
        ),
    ]
