# Generated by Django 4.2.5 on 2023-10-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0013_room_image1_room_image2_room_image3_room_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='static/rooms/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='static/rooms/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='static/rooms/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='static/rooms/'),
        ),
    ]
