# Generated by Django 4.2.5 on 2023-10-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0014_alter_room_image1_alter_room_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='image4',
            new_name='image0',
        ),
    ]
